name: Deploy Wambda

on:
  push:
    branches:
      - main
      - release/**

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.6
        with:
          fetch-depth: 2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4.0.2
        with:
          role-to-assume: "arn:aws:iam::748157940656:role/gh-actions"
          aws-region: us-west-2

      - name: Deploy Base Resources
        uses: aws-actions/aws-cloudformation-github-deploy@v1
        with:
          name: wambda-base
          template: devops/cfn-base.yaml
          no-fail-on-empty-changeset: "1"
          capabilities: CAPABILITY_NAMED_IAM
          
      - name: Deploy Base Resources
        uses: aws-actions/aws-cloudformation-github-deploy@v1
        with:
          name: wambda-base
          template: devops/cfn-base.yaml
          no-fail-on-empty-changeset: "1"